### ISSUE TITLE
[TD2][T1] Clean Browser Cache

### ISSUE THREAD

**Issue by edumargra** [UB-ES-2020/Mooving#108]
# Cache Bug
Study and find how to set-up vue-cli-service built so each new version can be seen without cleaning the browser cache.

- [x] Study vue-cli-service documentation
- [x] Apply fix

# Attention
For the fix to work, you will have to use the same tab and clean the cache beforehand.

**Comment by edumargra** [comment]
For the fix to work, you will have to use the same tab and clean the cache beforehand.

**Comment by lwangwan** [comment]
> For the fix to work, you will have to use the same tab and clean the cache beforehand.

Sorry Edu....Con F5 ya basta para refrescar los cambios. No hace falta que sea misma tab ni limpiar cache.

**Comment by edumargra** [comment]
ありがとうううううううううう
