### ISSUE TITLE
[US15][T2.2] Backend: Moto Reservation (Endpoints)

### ISSUE THREAD

**Issue by SrLimoncio** [UB-ES-2020/Mooving#109]
- [x]  Create EndPoint [GET] (TABLE RESERVATION) Para ver si está reservada antes de darle a start.
- [x]  Create EndPoint [POST] (TABLE RESERVATION)
- [x]  Create EndPoint [PUT] (TABLE RESERVATION)

**Comment by edumargra** [comment]
@SrLimoncio , me lo he mirado en la pull request, creo que es mejor *dividir-lo en dos endpoints*, uno para _reserve_ y una para _start_, ya que son funcionalidades diferentes (aunque trabajen sobre la misma tabla).

**Comment by SrLimoncio** [comment]
@edumargra Me parece buena idea, muchas gracias por la aportación. Ya lo he modificado, creando dos endpoints: Start y Reserved
