### ISSUE TITLE
[US14.1][T4]Client: Filter motos JSON

### ISSUE THREAD

**Issue by miguelMarchPiris** [UB-ES-2020/Mooving#113]
- [x] El endpoint tendría que incluir
- [x] Comentar esto pq no esta decidido :)
{
"km_restantes": 
}

**Comment by miguelMarchPiris** [comment]
@lwangwan Deberíamos hablar o documentar que se supone que pasa en cada caso. 
Es decir. Necesito saber que llegará al Backend en cada caso.

Para cada posible cosa que se envíe (yo diría que solo tendría que ser **model_generic**: basic/premium, y **more_km_restantes** int  ) necesito saber que me llega en caso de que los filtros estén activos, y en caso de que NO. 

Propongo lo siguiente:
ejemplo 1: todos los filtros puestos.
```
{
"model_generic":"basic",
"more_km_restantes" : 10
}
```
ejemplo 2: ningún filtro. (NADA)
```
{
"model_generic":"all",
"more_km_restantes" : 0
}
```
las combinaciones restantes se harían teniendo en cuenta lo que he puesto arriba. Lo escribo igualmente, pero seguro que te haces la idea.

ejemplo 3: solo el modelo
```
{
"model_generic":"basic",
"more_km_restantes" : 0

}
```
ejemplo 4: solo more_km_restantes
```
{
"model_generic":"all",
"more_km_restantes" : 10
}
```

**Comment by miguelMarchPiris** [comment]
Del backend al frontend:
@lwangwan  Necesito que me digas que esperas en el frontend. 
Yo pensaba pasarte las cosas como antes, con la distancia como "distance" y el resto de cosas de motoclient.

**Comment by lwangwan** [comment]
> @lwangwan Deberíamos hablar o documentar que se supone que pasa en cada caso.
> Es decir. Necesito saber que llegará al Backend en cada caso.
> 
> Para cada posible cosa que se envíe (yo diría que solo tendría que ser **model_generic**: basic/premium, y **more_km_restantes** int ) necesito saber que me llega en caso de que los filtros estén activos, y en caso de que NO.
> 
> Propongo lo siguiente:
> ejemplo 1: todos los filtros puestos.
> 
> ```
> {
> "model_generic":"basic",
> "more_km_restantes" : 10
> }
> ```
> 
> ejemplo 2: ningún filtro. (NADA)
> 
> ```
> {
> "model_generic":"all",
> "more_km_restantes" : 0
> }
> ```
> 
> las combinaciones restantes se harían teniendo en cuenta lo que he puesto arriba. Lo escribo igualmente, pero seguro que te haces la idea.
> 
> ejemplo 3: solo el modelo
> 
> ```
> {
> "model_generic":"basic",
> "more_km_restantes" : 0
> 
> }
> ```
> 
> ejemplo 4: solo more_km_restantes
> 
> ```
> {
> "model_generic":"all",
> "more_km_restantes" : 10
> }
> ```

Había pensado en que en vez de un POST con parametros 
```
{ "model_generic":,
 "more_km_restantes" : }
```
Es más bien un GET, llamando a algún resource, por ejemplo: 
```
"/motos/<string:modelGeneric>/<int:moreKmRestantes>"
 "/mechanicMotos/<string:modelGeneric>/<int:moreKmRestantes>"
```
Porque con el filter no estamos pasando nuevos recursos al servidor (POST), sino recuperar recursos del servidor(GET).
Y están bien pensados las combinaciones, 
los <string:modelGeneric> serán: .../all/..., .../basic/..., .../premium/...
<int:moreKmRestantes> serán enteros de 5 a 50 saltando de 5 en 5 (50 ~= 50+)

**Comment by lwangwan** [comment]
> Del backend al frontend:
> @lwangwan Necesito que me digas que esperas en el frontend.
> Yo pensaba pasarte las cosas como antes, con la distancia como "distance" y el resto de cosas de motoclient.

De acuerdo. Y puedes mirar El issue [US30][T2] Moto Page_client ? Decidimos añadir la información de id de los motos a los jsons relacionados con motos, ej: json_clientMoto(). Lo digo por si hay conflictos de merge, lo tengas en cuenta, y mantener esa información de id.

**Comment by lwangwan** [comment]
> > @lwangwan Deberíamos hablar o documentar que se supone que pasa en cada caso.
> > Es decir. Necesito saber que llegará al Backend en cada caso.
> > Para cada posible cosa que se envíe (yo diría que solo tendría que ser **model_generic**: basic/premium, y **more_km_restantes** int ) necesito saber que me llega en caso de que los filtros estén activos, y en caso de que NO.
> > Propongo lo siguiente:
> > ejemplo 1: todos los filtros puestos.
> > ```
> > {
> > "model_generic":"basic",
> > "more_km_restantes" : 10
> > }
> > ```
> > 
> > 
> > ejemplo 2: ningún filtro. (NADA)
> > ```
> > {
> > "model_generic":"all",
> > "more_km_restantes" : 0
> > }
> > ```
> > 
> > 
> > las combinaciones restantes se harían teniendo en cuenta lo que he puesto arriba. Lo escribo igualmente, pero seguro que te haces la idea.
> > ejemplo 3: solo el modelo
> > ```
> > {
> > "model_generic":"basic",
> > "more_km_restantes" : 0
> > 
> > }
> > ```
> > 
> > 
> > ejemplo 4: solo more_km_restantes
> > ```
> > {
> > "model_generic":"all",
> > "more_km_restantes" : 10
> > }
> > ```
> 
> Había pensado en que en vez de un POST con parametros
> 
> ```
> { "model_generic":,
>  "more_km_restantes" : }
> ```
> 
> Es más bien un GET, llamando a algún resource, por ejemplo:
> 
> ```
> "/motos/<string:modelGeneric>/<int:moreKmRestantes>"
>  "/mechanicMotos/<string:modelGeneric>/<int:moreKmRestantes>"
> ```
> 
> Porque con el filter no estamos pasando nuevos recursos al servidor (POST), sino recuperar recursos del servidor(GET).
> Y están bien pensados las combinaciones,
> los string:modelGeneric serán: .../all/..., .../basic/..., .../premium/...
> int:moreKmRestantes serán enteros de 5 a 50 saltando de 5 en 5 (50 ~= 50+)

Ah perdón, He mirado un poco lo que haces, estás implementando un GET con parametros, verdad? Vale, entonces está bien. Miraré cómo pasar las infos con axios.get("path", {...})

**Comment by lwangwan** [comment]
No consigo pasar las infos con axios.get("path", {...}) @miguelMarchPiris

**Comment by lwangwan** [comment]
ya esta solucionado, gracias Miguel. 
usar axios.get(path, {
        params: {
          model_generic: this.model_generic,
          more_km_restantes: this.more_km_restantes
        }
      })
Y no directamente axios.get(path, parameters) como en login
