### ISSUE TITLE
[US15][T3] JSON: Moto Reservation

### ISSUE THREAD

**Issue by SrLimoncio** [UB-ES-2020/Mooving#114]
RESOURCES:
- RESERVE
    - PARA GET:
        - [x] **reserve/<string:client_email>**
    - PARA POST:
        - [x] **reserve/ con parámetros <string:client_email> y <int:moto_id>**

- ACTIVE
    - PARA GET:
        - [x] **start/<string:client_email>**

***

JSONS:
Ambos GETs retornarán el mismo tipo de información que retorna el GET de ClientMotos
El POST de reservar retornará un mensaje con la hora correcta

- RESERVE
    - PARA GET:
        - [x]  como **reserved_moto** (ver más abajo)
    - PARA POST:
        - [x]  **{"message": 'You have until XX:XXh to start the motorbike', "remaining_time": "hh:mm" }, 201**

- ACTIVE
    - PARA GET:
        - [x]  como **reserved_moto** (ver más abajo)

Para GET de START
> "start_moto": {
        "id": 
        "matricula": 
        "model_generic": 
        "km_restantes": 
        "address":
        "last_coordinate_latitude":
        "last_coordinate_longitude":
        "distance": 
    }

Para GET de reserve
> "reserved_moto": {
        "id": 
        "matricula": 
        "model_generic": 
        "km_restantes": 
        "address":
        "last_coordinate_latitude":
        "last_coordinate_longitude":
        "distance": 
    },
  "message": 'You have until XX:XXh to start the motorbike', 
  "remaining_time": "hh:mm"

**Comment by rchacoma8** [comment]
@SrLimoncio Creo que sí necesito un método GET, hará más fácil la lógica de mostrar elementos, además, así podemos actualizar los datos cada vez que se cambia de página

**Comment by rchacoma8** [comment]
Oke, para esta Tarea se necesita Post para reservar por primera vez y GET para obtener las reservas.

PUT para modificar a Start es otra tarea US16
DELETE es también otra tarea US15.1

**Comment by rchacoma8** [comment]
@SrLimoncio Necesitaré método DELETE también

**Comment by rchacoma8** [comment]
@SrLimoncio Creo que para cumplir el Acceptance Criteria de la US15: 
> The client can only reserve a moto if no other moto is already reserved or running by them.

También necesitamos un GET de las motos que están en estado Activo por ese usuario

**Comment by SrLimoncio** [comment]
@rchacoma8 el get el mismo resource que el post? id moto y email cliente

**Comment by rchacoma8** [comment]
Para reservar (motos **RESERVED**): 
GET: reserve/string:client_email
POST: reserve/ con parámetros: string:client_email y int:moto_id

Debe retornar el json que suele ver el cliente de una moto.

**Comment by rchacoma8** [comment]
Para start (motos **ACTIVE**): 
GET: start/string:client_email

Debe retornar el json que suele ver el cliente de una moto.

**Comment by SrLimoncio** [comment]
@rchacoma8 ya esta implementado, cuando haga el merge lo tendrás, en el issue tienes mas información

**Comment by rchacoma8** [comment]
Ejemplo de json
`
"reserve_moto": {
        "id": 2,
        "matricula": "2222-MMM",
        "model_generic": "basic",
        "km_restantes": 80.0,
        "address": "Al Kufrah, Libia",
        "last_coordinate_latitude": 23.4431,
        "last_coordinate_longitude": 23.4433,
        "distance": 33
    }`

**Comment by SrLimoncio** [comment]
@rchacoma8 En principio ya estaría todo implementado, cualquier cosa comentamela.

**Comment by rchacoma8** [comment]
@SrLimoncio me he dado cuenta de que falta enviar desde backend si la moto estaba reservada, el mensaje que indica hasta qué hora tiene.
En el GET de reserve

EL json tendría:
 - [x] reserved_moto
 - [x] remaining_time
