### ISSUE TITLE
[US15.1][T4] JSON: Cancel reservation moto

### ISSUE THREAD

**Issue by miguelMarchPiris** [UB-ES-2020/Mooving#161]

**Comment by miguelMarchPiris** [comment]
en el backend con el siguiente url se espera:

`/reserved/<string:client_email>/<int:moto_id>`
No se esperan parámetros adicionales.


En caso de que todo vaya bien se devolverá:

`{"message": "Reserved Moto DELETED successfully"}, 200`

**Comment by lwangwan** [comment]
Implementado en Us15.1 t2 backend cancel reservation.
Cierro este issue
