### ISSUE TITLE
[US13][T3] Map

### ISSUE THREAD

**Issue by SrLimoncio** [UB-ES-2020/Mooving#179]
- Resource
```
URL: <url base>/motos
Body: { client_coordinate_latitude, client_coordinate_longitude, model_generic, more_km_restantes}
```

##
##

- JSON (Mismo retorno que listar todas las motos para el cliente)
```
"motos": [
        {
            "id":
            "matricula":
            "model_generic":
            "km_restantes":
            "last_coordinate_latitude":
            "last_coordinate_longitude":
            "distance":
        }
        ...
        ]
```

**Comment by ireneGarciaFernandez** [comment]
Como te he comentado en la daily para coger las coordenadas que le mandaré des de el frontend necesitamos un endpoint y su get...
Ya me dirás que enpoint pretendes usar y con que nombres quieres los parametros o como quieres que te lo envie ovo/

**Comment by SrLimoncio** [comment]
@ireneGarciaFernandez He actualizado la descripción, coméntame lo que sea.

**Comment by ireneGarciaFernandez** [comment]
Todo correcto y fantastico 💯
