### ISSUE TITLE
[US21][T3] Delete Account

### ISSUE THREAD

**Issue by SrLimoncio** [UB-ES-2020/Mooving#182]
RESOURCES:
- Account
    - PARA DELETE:
        - [x] `<url>/client/<string:email_client>` y body: `{"password": password}`

***

JSONS:
- RESERVE
    - PARA DELETE:
        - [x]  Si el correo pasado no pertenece a ningún cliente: `{'message': 'ERROR: There is no client with email [{client_email}] .'}, 404`
        - [x]  Si la contraseña no es correcta: `{'message': 'ERROR: The password is not correct.'}, 400`
        - [x]  Si el cliente tiene un trayecto iniciado: `{'message': 'ERROR: The account cannot be deleted because you have a journey started'}, 401`
        - [x]  Si todo ha ido bien: `{"message": "Client DELETED successfully"}, 200`

**Comment by SrLimoncio** [comment]
@edumargra que resources me envías? Se que envías el email del cliente y la contraseña, pero se envían por url o por el body?
Y que JSON necesitas?

**Comment by edumargra** [comment]
@SrLimoncio no estoy seguro la verdad..
[Aqui](https://stackoverflow.com/questions/299628/is-an-entity-body-allowed-for-an-http-delete-request) dicen que la url debe identificar uniquivocamente el _resource_, que seria el usuari@ (email), **sin embargo**, en cuanto a la contrasena no dicen nada, quiza es mas seguro por body o quiza tiene la misma seguridad, tu que opinas?

_en el caso que_ resource sea cliente, quiza el correo podria ir por url i la contrasenya por body?

*en cuanto el json de retorno* simplemente con un _mensaje ok, 200_ o _mensaje error, 400_ ya me serviria!

**Comment by edumargra** [comment]
@SrLimoncio i per ser consistents amb el resource anterior de delete client, podries fer que si no hay body, que no pasa nada, porque yo ya controlo que tenga que haber body para hacer la llamada

**Comment by SrLimoncio** [comment]
@edumargra He actualizado el JSON de la tarea. Compruébalo y dime tu opinión. En cuanto me confirmes hare el Pull Request.

**Comment by edumargra** [comment]
@SrLimoncio me parece todo bien, *excepto* el status code de los errores, preferiria que fueran todos diferentes asi puedo mostrar un mensaje relativo a ellos, podrias hacer que fueran del tipo 40X?

**Comment by SrLimoncio** [comment]
@edumargra Ya lo he actualizado. Con tu ayuda me ha sido sencillo definir los status code.

**Comment by edumargra** [comment]
@SrLimoncio buen resultado, un placer companero!
