### ISSUE TITLE
[US19][T3] Notify Error Moto

### ISSUE THREAD

**Issue by SrLimoncio** [UB-ES-2020/Mooving#184]
- Resource POST
```
URL: <url base>/notifyError/<id_moto>
```

##
##

- JSON (Mismo retorno que listar todas las motos para el cliente)

 Caso correcto:
```
"message": {"Correctly reported error "}, 201
```
Caso error no se encuentra la moto:
```
"message": {"Moto not found"}, 404
```
Caso error interno:
```
"message": {"Internal error when reporting the error"}, 500
```

**Comment by edumargra** [comment]
@SrLimoncio , creo que esto requerira un nuevo endpoint..

**que necessito:** un endpoint donde enviar que moto quiero crear una alerta
**que me das:** _mensaje ok, 200_ o _mesnaje error, 400_

De manera intuitiva, creo que solo se necessita la id de la moto, ya que al usuario no le salen motos que esten utilizando otros, aunque no se si deberiamos controlar algo

lo que no se es que tipo de llamada sera, alguna idea?

**Comment by edumargra** [comment]
@SrLimoncio lo estoy pensando y no se si *comentarle al PO* que no hace falta que el *Alert* este siempre disponible al usuario, asi que quiza no hace falta ni que pienses en parar/desreservar la moto.. aunque deberia ser bastante transparente para ti.

**Comment by edumargra** [comment]
El **PO** ha confirmado que se debe poder clicar el boton **Alert** en todo momento

**Comment by SrLimoncio** [comment]
@edumargra  aparte de poner el estado de la moto a ALERT, el cliente da algo mas? Como una descripción o algo? A parte, implemento un registro (ejemplo: guardando el usuario que la creo, fecha y hora, motivo) de las alertas que tiene una moto?

**Comment by edumargra** [comment]
recuerda que soy @edumargra , creo que sin querer notificas al profe..

>aparte de poner el estado de la moto a ALERT, el cliente da algo mas?

Ahora mismo este no es el caso, simplemente tiene el boton de ALERT, puesto que el PO tampoco se fia de que el usuario sepa que error le passa..

> A parte, implemento un registro (ejemplo: guardando el usuario que la creo, fecha y hora, motivo) de las alertas que tiene una moto?

Con lo que se pide ahora mismo, esto no haria falta, tan solo cambiar el estado, no?

**Comment by SrLimoncio** [comment]
@edumargra le comente sin error gracias por fijarte, vale, entonces implemento que cambie el estado. Implemento un post para /notifyerror/<id_moto>, que opinas?

**Comment by edumargra** [comment]
@SrLimoncio si, me parece lo mas adecuado!

gracias por estar atento

**Comment by SrLimoncio** [comment]
@edumargra He actualizado la descripción de la API. Coméntame lo que sea.

**Comment by edumargra** [comment]
@SrLimoncio perfect
