### ISSUE TITLE
[US34][T3] Modify Personal Info

### ISSUE THREAD

**Issue by SrLimoncio** [UB-ES-2020/Mooving#186]
/notifyError/<id_moto>

- Resource PUT
```
URL: <url base>/profile/<string:email>
Body: { name, iban, dni_nie, email} (No son obligatorios rellenar todos los campos)
```

##
##

- JSON 
Caso correcto:
```
{"message": "Client profile modified successfully"}, 200
```
Caso cliente no encontrado:
```
{"message": "Client with this email doesn't exist"}, 404
```
Caso cliente introduce un correo que ya esta en uso:
```
{"message": "The new email is already in use"}, 405
```
Caso cliente introduce un DNI/NIE que ya esta en uso:
```
{"message": "The new DNI/NIE is already in use"}, 406
```
Caso error interno:
```
{"message": "Error Modify client profile"}, 500
```

**Comment by edumargra** [comment]
@SrLimoncio  haras un PUT en el resource de cliente con todos los campos en el body, verdad?

**Comment by SrLimoncio** [comment]
@edumargra He actualizado la descripción de la API. Coméntame lo que sea.

**Comment by edumargra** [comment]
@SrLimoncio me lo estoy mirando, y hay un typo en la url, verdad?
ahora que lo pienso, tmb deberias controlar que pasa si otro usuario con el mismo correo o dni ya existe (estos dos atributos deben der unicos), no?

**Comment by SrLimoncio** [comment]
@edumargra En principio no debería haber un usuario con correo idéntico a otro, ni dni debido a que en la bases de datos están en únicos:
```
dni_nie = db.Column(db.String(9), nullable=False, unique=True)
email = db.Column(db.String(50), nullable=False, unique=True)
```

O te refieres a que si cuando modifica el perfil pone un correo que ya existe?

**Comment by edumargra** [comment]
>O te refieres a que si cuando modifica el perfil pone un correo que ya existe?

@SrLimoncio si, a eso me refiero
me parece bien los cambios que has anadido
