### ISSUE TITLE
[US3][T3] Add New Motos

### ISSUE THREAD

**Issue by miguelMarchPiris** [UB-ES-2020/Mooving#191]
BACKEND
Aquí defino las cosas que me gustaría recibir en el BACKEND y el formato en el que me gustaría recibirlas:

Propongo el path:
`<urlbase>/moto`

El JSON tendrá el siguiente estilo:
`
{ "license_plate": "1111-MMM", "model_generic": "basic" }
`
**license_plate** un String de 8 caracteres (no se si hay un formato muy definido o no) y **genérico** un string entre los siguientes {premium, basic} 

QUE DEVOLVER AL FRONTEND:

todo bien:
`{"message": "Moto added successfully"}, 200`

En caso de que haya otra moto con la misma matrícula pensaba devolver un error especial, dado que podría ser útil para uno de los acceptance criteria que salen en Trello
(8. **On confirmation**, if there is a motorbike with the same _License plate_, highlight the field in red and show message "There is already a motorbike with that license plate .")

Por lo tanto propongo devolver un mensaje muy similar al que pone el el acceptance criteria, además del status code 409, que es el status code que se utiliza para referirse a que hay un conflicto porque ya existe un resource igual (o con características únicas iguales).

`{"message":"There is already a motorbike with license plate [1234-KOP]."},409`

En caso de que la matrícula no tenga un formato válido 
`{"message": "ERROR: The format of the license plate is not valid."}, 400`

En caso de que el model_generic no sea i basic ni premium:
`{"message": "ERROR: model_generic should be either basic or premium."}, 400`

**Comment by ireneGarciaFernandez** [comment]
Una duda que comenté al PO fueron los campos, el frontend solo rellenará license Plate y Type, lo demás estaría predefinido en el backend si te parece mejor porque creo que el paso del frontend enviando parametros predefinidos al backend para que los escriba lo encuentro un poco innecesario, pero si lo ves primordial no me importa añadirlo.
Asi que la idea sería:
`{ "license_plate": "1111-MMM", "model_generic": "basic" }`

En si segun los acceptance criteria el backend solo deberia enviar una confirmación de si ha sido añadida o de si ya exite una moto con esa matricula no sería necesario enviar los datos de la moto...Porque inmediatamente después de añadirla ya volverá a la lista y se verá reflejado en esa.

**Comment by miguelMarchPiris** [comment]
Okay, ahora lo actualizo.

**Comment by miguelMarchPiris** [comment]
Ey, me he dado cuenta de que hay otro problema posible, que el modelo o la matrícula no sean válidos. En ambos casos devolveré un mensaje explicativo con un 400.

**Comment by ireneGarciaFernandez** [comment]
perfecto~

**Comment by miguelMarchPiris** [comment]
@ireneGarciaFernandez He pensado que igual es mejor utilizar 
**model_generic** en lugar de **type**, porque es más concreto y en otros métodos se utiliza también de esta nomenclatura.
`{ "license_plate": "1111-MMM", "model_generic": "basic" }`

**Comment by ireneGarciaFernandez** [comment]
> 
> 
> @ireneGarciaFernandez He pensado que igual es mejor utilizar
> **model_generic** en lugar de **type**, porque es más concreto y en otros métodos se utiliza también de esta nomenclatura.
> `{ "license_plate": "1111-MMM", "model_generic": "basic" }`

Vale, lo tendré en cuenta, aunque creo que hay en otros tambien se usa type no se si habría que informar para que siguiesemos siempre la nomenclatura...

**Comment by SrLimoncio** [comment]
@miguelMarchPiris @ireneGarciaFernandez Aceptada la Pull Request, por parte del backend hecho por miguel se cumple lo escrito.
