### ISSUE TITLE
[US18][T3] Client stops the moto

### ISSUE THREAD

**Issue by miguelMarchPiris** [UB-ES-2020/Mooving#193]
- **Backend:**

Propongo que el BACKEND reciba en la misma url que los el resource start
`<urlbase>/start`

PUT 
el método PUT debería pasar/recibir en la url los valores:
`
start/string:client_email/int:moto_id
`

- **Frontend:** 

```
{'message_status': 'Ok',
'message': 'Motorbike stoped successfully'},
200
```

```
{'message_status': "Not Found",
'message': "Client with email {} is not riding motorbike with id [{}]. "}, 404
```

```
{'message_status': "Internal Error",
                    'message': "Internal Server Error. "}, 500
```

**Comment by rchacoma8** [comment]
@miguelMarchPiris Imagino que es una llamada al método **PUT** de /start, ya que queremos actualizar el estado.


Creo que el método PUT debería pasar/recibir en la url los valores:
`
start/string:client_email/int:moto_id
`

Y al ser un método PUT, ya cambiaría dentro el estado de la moto y otras acciones.



Como respuesta,
```
message_status: Ok
message: Motorbike stoped successfully
status: 200
```

```
message_status: Not Found
message: Client with email {} is not riding motorbike with id {}
status: 404
```

Supongo que para este sprint no deberíamos tener el timer de 30 segundos, ¿no?

Si se te ocurre algún otro posible error, feel free

**Comment by rchacoma8** [comment]
De momento no se me ocurre nada más que se pueda necesitar, tho

**Comment by miguelMarchPiris** [comment]
No se si debería ser un PUT o un DELETE. Por un lado estamos borrando una fila de la tabla RR, pero realmente no estamos cambiando los Resources que están relacionados (Moto y Client). Aún así creo que tienes razón y que el PUT se adapta mejor. 

No se si es mejor pasar las cosas por la URL o por parámetros. Pero igualmente no veo pegas a ninguna de las dos así que nos quedamos con lo que has puesto (URL). 

Así que por mi parte todo OKAY.

**Comment by rchacoma8** [comment]
Bueno, creo que esto depende de cómo se gestione en el backend.
Queremos cambiar el estado de la moto, entonces  desde este punto de vista creo que es un PUT.

Dentro de este PUT, se borrará de la fila de motos RR (era la de motos que están running?) pero se debe guardar en algún lugar para poder luego mostrar el historial etc.

En los PUT se pasan los identificadores por URL y aquello que se quiere cambiar en el body, pero nosotros no podemos cambiar el estado mediante json, por eso creo que el body debe estar vacío.

En verdad, tienes razón en cuanto a que es relativo, depende internamente cómo lo gestionemos, si llamada a DELETE o a PUT, mientras que internamente haga lo que debe hacer. Supongo que esto lo tendrás que decidir tú y avisarme de cómo lo vas a implementar.

**Comment by rchacoma8** [comment]
@lwangwan @SrLimoncio Estabais de reviwers de las APIs. Do you approve?

**Comment by lwangwan** [comment]
> @lwangwan @SrLimoncio Estabais de reviwers de las APIs. Do you approve?

Me parece bien un PUT.  Tampoco sé cuál es mejor, pasar las cosas por la URL o por parámetros.

**Comment by SrLimoncio** [comment]
El backend  de esta tarea cumple con lo prestablecido en la descripción. Todo correcto.
