### ISSUE TITLE
[US32][T3] Delete Moto

### ISSUE THREAD

**Issue by rchacoma8** [UB-ES-2020/Mooving#198]
- **Backend**
URL: /moto/<int:moto_id>
(No hacen falta más parámetros).

##
##

- **Frontend**

1. Respuesta: Todo correcto.
```
{'message_status': 'Ok',
'message': 'Motorbike with id [{}] deleted successfully.'},200
```

2. Respuesta: No encontrado.
```
{'message_status': 'Not Found',
'message': 'Motorbike with id [{}] not found'}, 404
```

3. Respuesta: Moto en estado activo.
```
{'message_status': 'Conflict',
'message': 'Motorbike with id [{}] is active and can not be deleted'}, 409
```

4. Respuesta: Moto en estado reservado.
```
{'message_status': 'Conflict',
'message': 'Motorbike with id [{}] is reserved and can not be deleted'}, 409
```
5. Respuesta: Internal error:
```
{'message_status': 'Internal Error',
'message': 'Internal Server Error during Delete Moto.'}, 500
```

**Comment by rchacoma8** [comment]
@miguelMarchPiris 
en el resource de /moto necesitamos un método DELETE que reciba el id de la moto:
`/moto/int:moto_id`

Como respuesta,
```
message_status: Ok
message: Motorbike with id [{}] deleted successfully
status: 200
```

```
message_status: Not Found
message: Motorbike with id [{}] not found
status: 404
```

**Comment by miguelMarchPiris** [comment]
Me gusta, ahora lo actualizo.

**Comment by rchacoma8** [comment]
@lwangwan @SrLimoncio Estabais de reviwers de las APIs. Do you approve?

**Comment by SrLimoncio** [comment]
@rchacoma8 @miguelMarchPiris El código hecho por miguel cumple con lo prestablecido aquí. Apruebo.
