### ISSUE TITLE
[US34][T1] Modify Personal Information

### ISSUE THREAD

**Issue by edumargra** [UB-ES-2020/Mooving#206]
Create the view for modifying the personal information of a client. 
- [x] **"Modify"** _primary button_ at the bottom of the personal info page
- [x] create new page of a form for the user to fill
- [x] with fields "Name", "Email", "IBAN", "DNI"
- [x] upheld the same norms as the registry form
- [x]  text with the current information
- [x] cancel button

**Comment by edumargra** [comment]
@lwangwan me podrias hacer un favor?
tu crees que es mejor poner **en el input** de los datos que tiene actualmente, que es _sencillo_ y asi _puede editar al gusto_
o es mejor *placeholder*, que _se va al edit_, _no tengo muy claro de como se hace con variables_

y te parece una tonteria lo de anadir boton de cancelar?

el codigo esta en la rama: US34T1_ModifyPersonalInformation

**Comment by lwangwan** [comment]
> @lwangwan me podrias hacer un favor?
> tu crees que es mejor poner **en el input** de los datos que tiene actualmente, que es _sencillo_ y asi _puede editar al gusto_
> o es mejor _placeholder_, que _se va al edit_, _no tengo muy claro de como se hace con variables_
> 
> y te parece una tonteria lo de anadir boton de cancelar?
> 
> el codigo esta en la rama: US34T1_ModifyPersonalInformation

Me parece suficiente con poner en el input, los datos que tiene actualmente. Es buena idea añadir boton de cancelar.

**Comment by edumargra** [comment]
@lwangwan gracias hermana, **big dragon fist bump**
