### ISSUE TITLE
[TD3] Pytest Fixture

### ISSUE THREAD

**Issue by miguelMarchPiris** [UB-ES-2020/Mooving#218]
Para conseguir que los tests se ejecuten mejor haremos que antes de ejecutar los tests se limpie (vacíe) de contenido la base de datos y se vuelva a llenar con el _sample_ de datos ya conocidos.

- [x] Dropear todos los items de las tablas como funcion
- [x] Llenar todos los items de las tablas como funcion
- [x] Llamarlas en el contexto adecuada
- [x] Integrar todo lo anterior en el fixture de tests

**Comment by edumargra** [comment]
@miguelMarchPiris gran commit

la rama es TD3_PitestFixture, verdad?

**Comment by miguelMarchPiris** [comment]
@edumargra Si, claro. Si algo no lo entiendes no dudes en preguntarme (aunque no creo que te pueda ayudar demasiado).

**Comment by edumargra** [comment]
@miguelMarchPiris al final he cambiado un tanto el modelo, no hacia falta ejecutar cosas externas, sino asegurarnos del entorno donde estabamos ejecutando las cosas.
