### ISSUE TITLE
[TR9] Coverage

### ISSUE THREAD

**Issue by miguelMarchPiris** [UB-ES-2020/Mooving#247]

**Comment by edumargra** [comment]
@miguelMarchPiris aixo no ho havies fet amb lo de pycharm?

**Comment by miguelMarchPiris** [comment]
@edumargra Si. Pero lo he puesto igualmente en Done pq no sabía como gestionarlo.

**Comment by edumargra** [comment]
@miguelMarchPiris lo pongo en Done entonces?

**Comment by miguelMarchPiris** [comment]
si
