### ISSUE TITLE
[US15][T1] Moto Reservation

### ISSUE THREAD

**Issue by edumargra** [UB-ES-2020/Mooving#95]
- [x] Create a **button** to reserve: "Reserve". 
- [x] On click button to reserve: call API (to change the state to "RESERVED")
- [x] On click button to reserve: it disappears and instead there appear two other buttons: in the left one called "**Cancel**" and on the right one called "**Start**"
- [x] On click button to reserve: there appears a new list with title "**Reserved Motorbike**" above the "**Available Motorbikes**" list on the motorbikes page **with an horizontal line**.
- [x] **Horizontal line** between lists
- [x] On clicked element in "Reserved Motorbike" list: open moto info page (there will appear the buttons to Cancel and Start)
- [x] Add disabled functionality
- [x] On click button to reserve, there must appear "You have until XX:XX to pick up the motorbike" in bold
- [x] On clicked element in "Reserved Motorbike" list: there must appear the proper time  "You have until XX:XX to pick up the motorbike" in bold

Behaviour: 
- [x] Each time a user clicks an item in the list of **Available Motorbike**, if they have already selected one, the button will be **NOT CLICKABLE** or **DISABLED** (what makes it with a distintive gray light color).
(- [ ] If the user cancels the reservation, all buttons to **Reserve** will turn **CLICKABLE** again <-- No es de esta US, es de la US15.1)
- [x] The client can only reserve a moto if no other moto is already reserved or **running** by them.

QUESTION: or de we want it clickable and a dialog to show the error (already reserved one)? 
-[ ] Comprobar cómo se retorna la hora para mostrarlo al cliente

Colours:  
- [x] The button of reservation must be gray # 343a40 and have green letters # 42b983
- [x] The button of "Start" must be gray # 343a40 and have green letters # 42b983
- [x] The button of "Cancel" must be of a pastel red colour (#FF6961) and letters in white.

**Comment by rchacoma8** [comment]
Questions:
Al realizar el PUT de reservar la moto, el backend cambia su estado a RESERVED, por lo que al realizar la llamada a GET de motos AVAILABLE ya no aparecerá.
El botón reservar estará debajo de la información, en el centro.
Los otros botones aparecen un poco más abajo para que no dé instintivamente de manera rápida
