### ISSUE TITLE
[US30][T2] Moto Page_client

### ISSUE THREAD

**Issue by edumargra** [UB-ES-2020/Mooving#96]
- [x] Modiffy json get moto/s to reflect fields. Tiene que añadir la dirección.
- [x] Enviar id desde el frontend.
- [x] Si quereis, poneros de acuerdo y revisad si os vale el get de moto. **Esto para lo que envia el BACKEND.**

**Comment by lwangwan** [comment]
Después de hablar, hemos quedado en que:

1.Hemos decido no usar el get de "/moto/<int:id>" porque pasa mucho más información de lo que necesita. 
2.Modificar los json que tenemos ahora para las listas de motos (ej: json_listmotos()), añadir información de id.
3.El id se enviará por frontend llamando un nuevo Resource: "/clientMoto/<int:id>"
4.En el backend buscará por id el moto, y devuelve la información que necesita de ese moto:
`return {'client_moto': xxx.json_clientMoto()}, 200`

    def json_clientMoto(self):
        data = {
            'id': 
            'matricula': 
            'model_generic': 
            'km_restantes': 
            'address': 
            'distance':
        }
        return data

**Comment by lwangwan** [comment]
> Después de hablar, hemos quedado en que:
> 
> 1.Hemos decido no usar el get de "/moto/int:id" porque pasa mucho más información de lo que necesita.
> 2.Modificar los json que tenemos ahora para las listas de motos (ej: json_listmotos()), añadir información de id.
> 3.El id se enviará por frontend llamando un nuevo Resource: "/clientMoto/int:id"
> 4.En el backend buscará por id el moto, y devuelve la información que necesita de ese moto:
> `return {'client_moto': xxx.json_clientMoto()}, 200`
> 
> ```
> def json_clientMoto(self):
>     data = {
>         'id': 
>         'matricula': 
>         'model_generic': 
>         'km_restantes': 
>         'address': 
>         'distance':
>     }
>     return data
> ```

@ireneGarciaFernandez 
Te parece bien que pasan las coordenadas? Por si luego queremos mostrar en una mapa, es más fácil por coordenadas? Y también me facilita el uso de algunas funciones... De momento, puedes no mostrarlos.

```
def json_xxx(self):
     data = {
         'id': 
         'matricula': 
         'model_generic': 
         'km_restantes': 
         'address': 
         'last_coordinate_latitude': 
         'last_coordinate_longitude': 
         'distance':
     }
     return data
```

**Comment by ireneGarciaFernandez** [comment]
> 
> 
> > Después de hablar, hemos quedado en que:
> > 1.Hemos decido no usar el get de "/moto/int:id" porque pasa mucho más información de lo que necesita.
> > 2.Modificar los json que tenemos ahora para las listas de motos (ej: json_listmotos()), añadir información de id.
> > 3.El id se enviará por frontend llamando un nuevo Resource: "/clientMoto/int:id"
> > 4.En el backend buscará por id el moto, y devuelve la información que necesita de ese moto:
> > `return {'client_moto': xxx.json_clientMoto()}, 200`
> > ```
> > def json_clientMoto(self):
> >     data = {
> >         'id': 
> >         'matricula': 
> >         'model_generic': 
> >         'km_restantes': 
> >         'address': 
> >         'distance':
> >     }
> >     return data
> > ```
> 
> @ireneGarciaFernandez
> Te parece bien que pasan las coordenadas? Por si luego queremos mostrar en una mapa, es más fácil por coordenadas? Y también me facilita el uso de algunas funciones... De momento, puedes no mostrarlos.
> 
> ```
> def json_xxx(self):
>      data = {
>          'id': 
>          'matricula': 
>          'model_generic': 
>          'km_restantes': 
>          'address': 
>          'last_coordinate_latitude': 
>          'last_coordinate_longitude': 
>          'distance':
>      }
>      return data
> ```

Si te lo facilita y es mejor, adelante~
Solo mostraré lo que estuvo descrito en la US 👍

**Comment by lwangwan** [comment]
> > > Después de hablar, hemos quedado en que:
> > > 1.Hemos decido no usar el get de "/moto/int:id" porque pasa mucho más información de lo que necesita.
> > > 2.Modificar los json que tenemos ahora para las listas de motos (ej: json_listmotos()), añadir información de id.
> > > 3.El id se enviará por frontend llamando un nuevo Resource: "/clientMoto/int:id"
> > > 4.En el backend buscará por id el moto, y devuelve la información que necesita de ese moto:
> > > `return {'client_moto': xxx.json_clientMoto()}, 200`
> > > ```
> > > def json_clientMoto(self):
> > >     data = {
> > >         'id': 
> > >         'matricula': 
> > >         'model_generic': 
> > >         'km_restantes': 
> > >         'address': 
> > >         'distance':
> > >     }
> > >     return data
> > > ```
> > 
> > 
> > @ireneGarciaFernandez
> > Te parece bien que pasan las coordenadas? Por si luego queremos mostrar en una mapa, es más fácil por coordenadas? Y también me facilita el uso de algunas funciones... De momento, puedes no mostrarlos.
> > ```
> > def json_xxx(self):
> >      data = {
> >          'id': 
> >          'matricula': 
> >          'model_generic': 
> >          'km_restantes': 
> >          'address': 
> >          'last_coordinate_latitude': 
> >          'last_coordinate_longitude': 
> >          'distance':
> >      }
> >      return data
> > ```
> 
> Si te lo facilita y es mejor, adelante~
> Solo mostraré lo que estuvo descrito en la US +1

Vale, thx. Ahora envio un pull request
