### ISSUE TITLE
[US30][T3] Moto page_client BACKEND

### ISSUE THREAD

**Issue by edumargra** [UB-ES-2020/Mooving#97]
- [x] Modify moto table and add street field to moto

**Comment by edumargra** [comment]
Sugerencia: Street es un String

**Comment by lwangwan** [comment]
no hace falta introducir manualmente la dirección, se obtiene de las coordenadas.
Pro: menos cambios en el código.
Contra: Escalabilidad https://operations.osmfoundation.org/policies/nominatim/
