### ISSUE TITLE
[US31][T1] Moto Page_Mechanic

### ISSUE THREAD

**Issue by edumargra** [UB-ES-2020/Mooving#98]
- [x] Shown License Plate and State in bold.
- [x] Show Time and km since last revision.
- [x] Show Time and km since it was added to the system.
- [x] Show Remaining battery and type.
- [x] Show Distance and Street.
- [x] Call API to get the information of the certain moto.(Different new endpoint  something like mechanicMotos but for one moto)

**Comment by ireneGarciaFernandez** [comment]
Añadir distance a la vista de mechanic moto info

**Comment by ireneGarciaFernandez** [comment]
Añadir type a la vista
